version: "3"
services:
  nginx:
    ports:
      - "80:80"
  rated-app-server:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node ./bin/www
